### ISSUE TITLE
Div "content" is empty

### ISSUE THREAD

**Issue by mmundi72** [OneGov/plonetheme.onegov#183]
On April 8, 2014 I asked concerning the extraction of the content of a page. That was handled in the follwing issue:
https://github.com/OneGov/plonetheme.onegov/issues/84

That worked so fare. But now it seems that something changed (maybe with the new release of www.zg.ch?): the content within the DIV id="content" is empty.

Can you please check on this and correct it? We rely on this DIV as we are showing some content from the website withing a separate web application...

Thanks for your feedback.

Best regards,
Mischa Mundwiler

**Comment by maethu** [comment]
Can you show me an example, where it's empty?

I'm not sure, whether we touched it or not.

**Comment by mmundi72** [comment]
As example on this page:
http://www.zg.ch/behoerden/finanzdirektion/steuerverwaltung

**Comment by maethu** [comment]
The div with id `content` is not empty on this page??

<img width="1264" alt="screen shot 2015-09-21 at 14 30 38" src="https://cloud.githubusercontent.com/assets/437933/9991801/7bcbbb3e-606d-11e5-84d3-9733dc7d9295.png">

**Comment by mmundi72** [comment]
OK, thanks for your feedback. I will tell that our developers....

**Comment by mmundi72** [comment]
Response from our developer:
The following page doesn't seem to be correct.

http://www.zg.ch/behoerden/finanzdirektion/steuerverwaltung/fristerstreckung-np

Can you please check on this as well?

**Comment by maethu** [comment]
Well, on this page there's  also a DIV with id `content`. 
<img width="1341" alt="screen shot 2015-09-22 at 08 43 47" src="https://cloud.githubusercontent.com/assets/437933/10012234/3cfaa642-6106-11e5-8080-f90f7902b196.png">

> Response from our developer:
The following page doesn't seem to be correct.

It would help if could say what's wrong or not correct? I mean the `#content` will be on nearly every page. I guess the Issue is somewhere else :question: :question: :confused:

**Comment by maethu** [comment]
@mmundi72 Any news on this one?

**Comment by mmundi72** [comment]
It seems that the problem has been resolved. Thanks for your support.
